## DB: Adjusted for:
## - container image version gradiant/ueransim:dev-b68de9b (tag dev-b68de9b)
##   this tag is claimed to support iperf 3 (we do not need it in our lab, but it's good to know)
## - four UEs to be initially created
## Note: initialMSISDN: '0000000001' - MSISDN part of the SUPI of the first UE attached; next UEs attached will be assigned consecutive MSISDN numbers.
## mcc: Mobile Country Code (part of SUPI)
## mnc: Mobile Network Code (part of SUPI)
## sst: Slice Service Type (part of S-NSSAI)
## sd: Slice Differentiator (part of S-NSSAI)
## tac: Tracking Area Code (tracking area respective cell/gNB belongs to - same as TAC of serving gNB)

image:
  registry: docker.io
  repository: gradiant/ueransim
  tag: dev-b68de9b
  pullPolicy: Always
  pullSecrets: []
  debug: false

amf:
  hostname: open5gs-amf-ngap

gnb:
  hostname: ueransim-gnb

mcc: '999'
mnc: '70'
sst: 1
sd: "0x111111"
tac: '0001'

ues:
  enabled: true
  count: 4
  initialMSISDN: '0000000001'
